name: Mini projet DevOps CI/CD

on:
  push:
    branches:
      - main

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t med2380/mini_devops:latest .
      # Étape 3 : Pousser l'image sur Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker login -u med2380 -p ${{ secrets.DOCKER_HUB_TOCKEN }}
          docker push med2380/mini_devops:latest