name: Mini projet DevOps CI/CD

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Configurer Docker Buildx (utile pour les builds avancés et cross-platform)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 3 : Mise en cache des couches Docker (accélère les builds successifs)
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Étape 4 : Connexion à Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 5 : Construction et push de l'image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .  # Répertoire contenant votre Dockerfile
          push: true  # Poussez l'image vers Docker Hub
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/mini_devops:latest
            ${{ secrets.DOCKER_USERNAME }}/mini_devops:${{ github.sha }}

      # Étape 6 : Déconnexion de Docker Hub
      - name: Logout from DockerHub
        run: docker logout
