name: mini_projet_docker_devops_ci_cd

on:
  push:
    branches:
      - main  # Exécuter le workflow uniquement sur la branche main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Utilise le secret DOCKER_USERNAME
          password: ${{ secrets.DOCKER_PASSWORD }}  # Utilise le secret DOCKER_PASSWORD

      # Étape 3 : Construire et pousser l'image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: med2380/mini_devops:latest  # Remplacez "med2380" par votre nom d'utilisateur Docker Hub
